---
title: 'R for Art Sundays'
date: '2019-05-26'
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
```

# Drrrawing with purrr

by [Antonio Sánchez Chinchón](https://twitter.com/aschinchon)

An R experiment to create images generated by sines, cosines and imagination. It takes advantage on the `accumulate` function from `purrr` package. Images are inspired in Sutcliffe pentagons.

Made with `tidyverse`

**Blog post explaining the experiment:** [Drrrawing with purrr](https://fronkonstin.com/2019/03/27/drrrawing-with-purrr/)

[Github repo with more details](https://github.com/aschinchon/drrrawing-with-purrr)


```{r code, message=FALSE, warning=FALSE, error=FALSE, fig.width=8, fig.height=8}

library(tidyverse)

# This function creates the segments of the original polygon
polygon <- function(n) {
  tibble(
    x    = accumulate(1:(n-1), ~.x+cos(.y*2*pi/n), .init = 0),
    y    = accumulate(1:(n-1), ~.x+sin(.y*2*pi/n), .init = 0),
    xend = accumulate(2:n,     ~.x+cos(.y*2*pi/n), .init = cos(2*pi/n)),
    yend = accumulate(2:n,     ~.x+sin(.y*2*pi/n), .init = sin(2*pi/n)))
}

# This function creates segments from some mid-point of the edges
mid_points <- function(d, p, a, i, FUN = ratio_f) {
  d %>% mutate(
    angle=atan2(yend-y, xend-x) + a,
    radius=FUN(i),
    x=p*x+(1-p)*xend,
    y=p*y+(1-p)*yend,
    xend=x+radius*cos(angle),
    yend=y+radius*sin(angle)) %>% 
    select(x, y, xend, yend)
}

# This function connect the ending points of mid-segments
con_points <- function(d) {
  d %>% mutate(
    x=xend,
    y=yend,
    xend=lead(x, default=first(x)),
    yend=lead(y, default=first(y))) %>% 
    select(x, y, xend, yend)
}

edges <- 9   # Number of edges of the original polygon
niter <- 310 # Number of iterations
pond <- 0.241  # Weight to calculate the point on the middle of each edge
step  <- 24  # Number of times to draw mid-segments before connect ending points
alph  <- 0.2288 # transparency of curves in geom_curve
angle <- 2.0807 # angle of mid-segment with the edge
curv <- 0.3584   # Curvature of curves
line_color <- "white" # Color of curves in geom_curve
back_color <- "gray20" # Background of the ggplot
ratio_f <- function(x) {log(x+1)} # To calculate the longitude of mid-segments

# Generation on the fly of the dataset
accumulate(.f = function(old, y) {
  if (y%%step!=0) mid_points(old, pond, angle, y) else con_points(old)
}, 1:niter,
.init=polygon(edges)) %>% bind_rows() -> df

# Plot
ggplot(df)+
  geom_curve(aes(x=x, y=y, xend=xend, yend=yend),
             curvature = curv,
             color=line_color,
             alpha=alph)+
  coord_equal()+
  theme(legend.position  = "none",
        panel.background = element_rect(fill=back_color),
        plot.background  = element_rect(fill=back_color),
        axis.ticks       = element_blank(),
        panel.grid       = element_blank(),
        axis.title       = element_blank(),
        axis.text        = element_blank()) -> plot

plot

```



-----


```{r, results='asis', echo=FALSE}

cat(
  " Compiled: ",
  as.character(Sys.Date()),
  sep = ""
)
```
