---
title: 'R for Art Sundays'
date: '2019-06-01'
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
```

# Crochet Patterns

by [Antonio Sánchez Chinchón](https://twitter.com/aschinchon)

An R experiment to create images generated by sines, cosines and imagination.

Made with `tidyverse`

<!-- Takes up too much memory for current version of rstudio.cloud -->
<!-- On [RStudio Cloud](https://rstudio.cloud/project/370892).  -->

**Blog post explaining the experiment:** [Crochet Patterns](https://fronkonstin.com/2018/10/14/crochet-patterns/)

*Dedicated to the memory of Pilar, my grandmother*

[Github repo with more details](https://github.com/aschinchon/crochet-patterns)


```{r code, message=FALSE, warning=FALSE, error=FALSE, fig.width=8, fig.height=8, dpi=600}

# Load the tidyverse
library(tidyverse)

# This function creates an individual pattern
pattern <- function(a, b, c = pi/2, d = pi/5, e = 4) {
  data_frame(
    x = accumulate(1:60, ~.x-sin((.y %% e)*c-ceiling((.y-1)/e)*d), .init = a),
    y = accumulate(1:60, ~.x+cos((.y %% e)*c-ceiling((.y-1)/e)*d), .init = b))
}

# I arrange patterns on a circle
t <- seq(0, 2*pi, length.out = 180)
centers <- data_frame(x = sin(t), y = cos(t))

# To initialize parameters of function pattern
c  <- 4.811
d  <- 5.301
e  <- 4

# This creates the plot
apply(centers, 1, function(r) pattern(a = r[1], 
                                      b = r[2],
                                      c = c,
                                      d = d,
                                      e = e)) %>% 
  bind_rows(.id="df") %>% 
  ggplot() +
  geom_path(aes(x, y, group = df), alpha = 0.05) + 
  coord_fixed()+
  theme_void() -> plot

plot

```



-----


```{r, results='asis', echo=FALSE}

cat(
  " Compiled: ",
  as.character(Sys.Date()),
  sep = ""
)
```
